# Generated by Django 4.0.4 on 2022-04-28 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=200)),
                ('omschrijving', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('barcode', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BierFles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vervaldatum', models.DateTimeField(verbose_name='vervaldatum')),
                ('hoeveelheid', models.IntegerField(default=0)),
                ('prijs', models.IntegerField(default=0)),
                ('bier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biercatalogus.bier')),
            ],
        ),
        migrations.CreateModel(
            name='BierConsumptie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelegenheid', models.CharField(max_length=200)),
                ('zuipdatum', models.DateTimeField(verbose_name='vervaldatum')),
                ('biertjes', models.ManyToManyField(to='biercatalogus.bierfles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
