# Generated by Django 4.0.4 on 2022-04-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biercatalogus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bier',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
