# Generated by Django 4.0.4 on 2022-04-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biercatalogus', '0002_alter_bier_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bier',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
    ]
