# Generated by Django 4.0.4 on 2022-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biercatalogus', '0003_bier_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bier',
            name='beercolor',
            field=models.CharField(choices=[('BLOND', 'BLOND'), ('BROWN', 'BROWN'), ('AMBER', 'AMBER')], default='BLOND', max_length=6),
        ),
        migrations.AddField(
            model_name='bier',
            name='content_cl',
            field=models.PositiveIntegerField(default=33),
        ),
    ]
